### ISSUE TITLE
Transgender villagers with carry on mod?

### ISSUE THREAD

**Issue by Aceplante** [Daripher/Female-Villagers#8] opened 2023-05-21 06:15 UTC
Whenever you place a male villager down afting picking him up with the carry on mod, it seems to convert into a female villager.

Also the tooltip of female villagers is entity.femalevillagers.female_villager

![2023-05-21_02 15 06](https://github.com/Daripher/Female-Villagers/assets/101857505/1de95ba7-095e-4895-b14d-3235ed35eeb9)

**Comment by Aceplante** [comment] 2023-05-25 23:41
Actually on thinking about it more, I feel like this might be on their end. Certain data isnt saved?

**Comment by Daripher** [comment] 2023-05-26 10:09
> Actually on thinking about it more, I feel like this might be on their end. Certain data isnt saved?

No, its on my end

**Comment by xFirefalconx** [comment] 2023-06-04 14:05
Mob Catcher mod also does this, I lost the only male villager after catching and releasing him with the tool 🙈 
Is there a possibility you can fix this for 1.18.2? My modpack is a bit unstable with this situation.

**Comment by Daripher** [comment] 2023-06-04 14:14
> Mob Catcher mod also does this, I lost the only male villager after catching and releasing him with the tool 🙈 Is there a possibility you can fix this for 1.18.2? My modpack is a bit unstable with this situation.

I'll check it soon

**Comment by Aceplante** [comment] 2023-06-07 00:08
oh, yea I forgot to specify but I use 1.18.2 as well

**Comment by Daripher** [comment] 2023-06-08 23:34
Duplicate of #7

**Closed as not planned by Daripher** 2023-06-08 23:34 UTC
Labels: bug, duplicate, incompatibility
